<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-4Q6IINH" failures="0" tests="5" name="Default test" time="9.212" errors="0" timestamp="2024-11-22T12:38:34 IST">
  <testcase classname="com.runner.TestRunner" name="@BeforeTest settUp" time="9.117">
    <failure type="java.lang.AssertionError" message="ERROR DURING BROWSER URL LAUCH">
      <![CDATA[java.lang.AssertionError: ERROR DURING BROWSER URL LAUCH
at org.junit.Assert.fail(Assert.java:89)
at com.base.BaseClass.lauchUrl(BaseClass.java:57)
at com.runner.TestRunner.settUp(TestRunner.java:20)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.beforeRun(TestRunner.java:627)
at org.testng.TestRunner.run(TestRunner.java:589)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- @BeforeTest settUp -->
  <testcase classname="com.runner.TestRunner" name="@AfterTest close" time="-1.732259314112E9">
    <skipped/>
  </testcase> <!-- @AfterTest close -->
  <testcase classname="com.runner.TestRunner" name="validUserNameAndPassword" time="0.0">
    <skipped/>
  </testcase> <!-- validUserNameAndPassword -->
  <testcase classname="com.runner.TestRunner" name="emptyUserAndPassword" time="0.0">
    <skipped/>
  </testcase> <!-- emptyUserAndPassword -->
  <testcase classname="com.runner.TestRunner" name="emptyUserAndPassword" time="0.0">
    <skipped/>
  </testcase> <!-- emptyUserAndPassword -->
  <testcase classname="com.runner.TestRunner" name="invalidUserNameAndPassword" time="0.0">
    <skipped/>
  </testcase> <!-- invalidUserNameAndPassword -->
  <testcase classname="com.runner.TestRunner" name="notSelectLocation" time="0.0">
    <skipped/>
  </testcase> <!-- notSelectLocation -->
</testsuite> <!-- Default test -->
